In [1]:
import geopandas as gpd
import sys
sys.path.append('..')
import osmnx as ox
import shapely
from transport_frames.indicators_area import *
from transport_frames.indicators_area import *

/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# initialization of services

In [2]:
# services

railway_stations = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/railway_station.geojson')
railway_roads = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/railway.geojson')
bus_stops = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/bus_stop.geojson')
fuel_stations = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/Копия fuel.geojson')
local_aerodrome = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/aerodrome.geojson')
local_aerodrome['geometry'] = shapely.centroid(local_aerodrome['geometry']).set_crs(local_aerodrome.crs)
international_aerodrome = local_aerodrome[local_aerodrome['aerodrome:type']=='international']
international_aerodrome['geometry'] = shapely.centroid(international_aerodrome['geometry']).set_crs(international_aerodrome.crs)

# nature objects
water = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/Копия water.geojson')
nature_reserve = gpd.read_file(f'/Users/polina/Desktop/github/transport_frames/data/Тульская_область/Копия nature_reserve.geojson')

capital =ox.geocode_to_gdf('N34389350',by_osmid=True)
districts_polygons = gpd.read_file('/Users/polina/Desktop/github/transport_frames/data/Тульская_область/district.geojson')
settlement_polygons = gpd.read_file('/Users/polina/Desktop/github/transport_frames/data/Тульская_область/settlement.geojson')
settlement_points = gpd.read_file('/Users/polina/Desktop/github/transport_frames/data/Тульская_область/Тульская_область_region_points.geojson')

# Graph creation

In [3]:
from transport_frames.graph import Graph

geocode=81993
polygon = ox.geocode_to_gdf(f'R{geocode}', by_osmid=True)
local_crs = 32637
g = Graph(polygon,local_crs)

2025-02-20 00:35:19.884 | INFO     | iduedu.modules.drive_walk_builder:get_drive_graph_by_poly:91 - Downloading drive graph from OSM, it may take a while for large territory ...

# Indicators

In [5]:
from transport_frames.indicators_area import *

In [6]:
indicator_distance_to_region_admin_center(capital,settlement_points,districts_polygons,g.graph,local_crs).head()

,name,geometry,distance_to_admin_center
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",115.7150
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",130.1660
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",81.6420
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",65.2820
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",109.1135

In [7]:
indicator_distance_to_federal_roads(settlement_points,districts_polygons,g.graph,local_crs).head()

,name,geometry,distance_to_federal_roads
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",36.0405
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",6.7490
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",9.0930
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",4.8230
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",15.5010

In [8]:
indicator_road_length(g.graph, districts_polygons).head()

,name,geometry,road_length
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",785.520134
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",1213.853873
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",1074.637098
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",1740.825543
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",1042.672048

In [9]:
indicator_reg_length(g.graph,districts_polygons).head()

,name,geometry,length_reg_1,length_reg_2,length_reg_3
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",0.000000,284.744026,500.776108
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",107.710276,170.099209,936.044388
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",78.487690,303.526233,692.623175
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",231.395153,262.418172,1247.012218
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",56.924065,206.902682,778.845301

In [4]:
indicator_connectivity_drive(settlement_points,g.graph,districts_polygons).head()

,name,geometry,connectivity
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",127.1600
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",152.1800
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",99.6300
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",105.5100
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",104.6825

In [13]:
indicator_service_count(districts_polygons,
                            fuel_stations=fuel_stations, 
                            local_aerodrome=local_aerodrome,
                            international_aerodrome=international_aerodrome, 
                            railway_stations=railway_stations,
                            bus_stops=bus_stops).head()

,name,geometry,railway_stations_number,fuel_stations_number,ports_number,local_aerodrome_number,international_aerodrome_number,bus_stops_number
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",0,1,0,0,0,8
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",1,3,0,0,0,48
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",2,13,0,0,0,79
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",2,26,0,0,0,116
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",2,6,0,0,0,29

In [14]:
indicator_service_accessibility(settlement_points, g.graph, districts_polygons,
                            fuel_stations=fuel_stations, 
                            local_aerodrome=local_aerodrome,
                            international_aerodrome=international_aerodrome,
                            railway_stations=railway_stations,
                            bus_stops=bus_stops).head()

,name,geometry,railway_stations_accessibility,fuel_stations_accessibility,ports_accessibility,local_aerodrome_accessibility,international_aerodrome_accessibility,bus_stops_accessibility
0,Арсеньевский район,"POLYGON ((319712.393 5950903.092, 319906.056 5...",137.500,136.750,None,129.875,None,129.37500
1,Белевский район,"POLYGON ((296002.715 5971313.180, 296090.881 5...",156.125,159.375,None,147.000,None,150.00000
2,Богородицкий район,"POLYGON ((424958.858 5954606.827, 425051.017 5...",80.000,76.625,None,103.000,None,79.56250
3,Веневский район,"POLYGON ((425947.184 6022267.642, 426062.021 6...",74.500,69.000,None,102.000,None,69.87500
4,Воловский район,"POLYGON ((416123.449 5924160.895, 416677.559 5...",90.250,89.875,None,111.375,None,93.78125

In [15]:
indicator_railway_length(railway_roads,districts_polygons,local_crs).head()

,name,geometry,railway_length_km
0,Арсеньевский район,"POLYGON ((319712.393 5950903.092, 319906.056 5...",0.000000
1,Белевский район,"POLYGON ((296002.715 5971313.180, 296090.881 5...",20.839681
2,Богородицкий район,"POLYGON ((424958.858 5954606.827, 425051.017 5...",83.893379
3,Веневский район,"POLYGON ((425947.184 6022267.642, 426062.021 6...",128.610032
4,Воловский район,"POLYGON ((416123.449 5924160.895, 416677.559 5...",82.777041

In [16]:
indicator_bus_routes(districts_polygons, polygon_gdf=polygon).head()

Parsing routes:   0%|          | 0/114 [00:00<?, ?it/s]/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/shapely/linear.py:88: RuntimeWarning: invalid value encountered in line_locate_point
  return lib.line_locate_point(line, other)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/shapely/linear.py:88: RuntimeWarning: invalid value encountered in line_locate_point
  return lib.line_locate_point(line, other)
Parsing routes:   1%|          | 1/114 [00:08<16:20,  8.68s/it]/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/shapely/linear.py:88: RuntimeWarning: invalid value encountered in line_locate_point
  return lib.line_locate_point(line, other)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
Parsing routes:   9%|▉         | 10/114 [00:08<01:06,  1.57it/s]/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/shapely/linear.py:88: RuntimeWarning: invalid value encountered in line_locate_point
  return lib.line_locate_point(line, other)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/shapely/linear.py:88: RuntimeWarning: invalid value encountered in line_locate_point
  return lib.line_locate_point(line, other)
/Users/polina/Desktop/tf2/venv/lib/python3.10/site-packages/iduedu/modules/routes_parser.py:263: UserWarning: В одном из маршрутов нет пути, пока не работаю с этим
  warnings.warn("В одном из маршрутов нет пути, пока не работаю с этим", UserWarning)
Parsing routes: 100%|██████████| 114/114 [00:08<00:00, 12.67it/s]

,name,geometry,bus_routes_count
0,Арсеньевский район,"POLYGON ((36.27046 53.67571, 36.27343 53.67505...",0
1,Белевский район,"POLYGON ((35.89856 53.85018, 35.90015 53.84679...",0
2,Богородицкий район,"POLYGON ((37.86240 53.73471, 37.86404 53.72565...",1
3,Веневский район,"POLYGON ((37.86087 54.34286, 37.86265 54.34249...",4
4,Воловский район,"POLYGON ((37.73668 53.45977, 37.74516 53.45518...",0

# terr

In [5]:
terr = districts_polygons.iloc[[4]]

In [16]:
gpd.GeoDataFrame(geometry=terr.geometry.centroid, crs=terr.crs)

                    geometry
4  POINT (38.04848 53.48318)

In [17]:
def indicator_terr_service_accessibility(graph: nx.MultiDiGraph, 
                                    terr: gpd.GeoDataFrame,
                                    fuel_stations: gpd.GeoDataFrame = None, 
                                    railway_stations: gpd.GeoDataFrame = None, 
                                    ports: gpd.GeoDataFrame = None,
                                    local_aerodrome: gpd.GeoDataFrame = None, 
                                    international_aerodrome: gpd.GeoDataFrame = None,
                                    bus_stops: gpd.GeoDataFrame = None) -> gpd.GeoDataFrame:
    
    sp = gpd.GeoDataFrame(geometry=terr.geometry.centroid, crs=terr.crs).reset_index()
    return indicator_service_accessibility(sp, graph, terr,
                            fuel_stations=fuel_stations, 
                            local_aerodrome=local_aerodrome,
                            international_aerodrome=international_aerodrome,
                            railway_stations=railway_stations,
                            bus_stops=bus_stops)


indicator_terr_service_accessibility(g.graph, terr,
                            fuel_stations=fuel_stations, 
                            local_aerodrome=local_aerodrome,
                            international_aerodrome=international_aerodrome,
                            railway_stations=railway_stations,
                            bus_stops=bus_stops)

NotImplementedError: float16 indexes are not supported